### ISSUE TITLE
How to define NDR

### ISSUE THREAD

**Issue by mengqingren** [uschwartz/nucMACC#10]
Dear Dr,
I'am wondering how to determine the NDR in nucMACC, whch module will output the NDR information. And if I want to compare the two conditional files including treated and ctrl with correspongding input files. Is it enough to obtain the DE nucleasome by running numMACC.
Thank you
Best

**Comment by uschwartz** [comment]
Hello,

Thank you for reaching out. I wanted to inform you that I am currently on paternity leave until the 1st of October. During this period, I will not be available to respond to emails or attend to work-related matters.

I appreciate your understanding and patience during this special time for my family. I will respond to your email as soon as possible upon my return.

best regards,
Uwe
