### ISSUE TITLE
The following chromosome names did not match between the bigwig files

### ISSUE THREAD

**Issue by davhum** [uschwartz/nucMACC#12]
I am trying this pipeline against hg38 genome. The pipeline gets most of the way through but then falls over with the following message: 

The following chromosome names did not match between the bigwig files
chromosome	length
chrUn_KI270420v1	      2321
chrUn_KI270744v1	    168472
chrUn_KI270583v1	      1400
chrUn_KI270363v1	      1803
chr1_KI270714v1_random	     41717
chrUn_KI270391v1	      1484
chr22_KI270737v1_random	    103838
chr15_KI270727v1_random	    448248
chrUn_KI270518v1	      2186
chrUn_KI270422v1	      1445
chr9_KI270720v1_random	     39050
chrUn_KI270382v1	      4215
chr1_KI270708v1_random	    127682
chrUn_KI270465v1	      1774

This message I believe comes from deeptools. I wonder if this is a warning message from deeptools or an actual error.  Should I be aligning to a hg38 genome with only full chr entries?

**Comment by uschwartz** [comment]
I would recommend using genome assemblies without haplotype/patch regions such as the Ensembl primary assembly files. Haplotype/patch regions are prone to produce artifacts and I am not sure that they prodvide reliable information about nucleosome organisation.  

Not sure when exactly (which process?) this message comes and I would need further information to figure out what happend exactly. The pipeline automatically produces the chromosome length information basically out of the bowtie index. It might happen that no reads align to those patches and they are lost in the bigwig files and deepltools will complain about that, but this should not run in an error and abort the run.

**Comment by davhum** [comment]
Thanks - you were spot on. I made a new bowtie2 index and was able to get past this point. I unfortunately have another error which I will post in another thread. 

The error reported in this thread was caused when running the following deeptools command:

computeMatrix reference-point -S
